/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Animal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'shortFact' : IDL.Text,
  'category' : IDL.Text,
  'conservationStatus' : IDL.Text,
  'facts' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
  'getAnimal' : IDL.Func([IDL.Nat], [Animal], ['query']),
  'getAnimalsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Animal)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Animal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'shortFact' : IDL.Text,
    'category' : IDL.Text,
    'conservationStatus' : IDL.Text,
    'facts' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
    'getAnimal' : IDL.Func([IDL.Nat], [Animal], ['query']),
    'getAnimalsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Animal)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };