/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DinosaurInput = IDL.Record({
  'era' : IDL.Text,
  'period' : IDL.Text,
  'diet' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'length' : IDL.Text,
  'interestingFact' : IDL.Text,
});
export const Dinosaur = IDL.Record({
  'id' : IDL.Nat,
  'era' : IDL.Text,
  'period' : IDL.Text,
  'diet' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'length' : IDL.Text,
  'interestingFact' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDinosaur' : IDL.Func([DinosaurInput], [], []),
  'getAllDinosaurs' : IDL.Func([], [IDL.Vec(Dinosaur)], ['query']),
  'getDinosaurById' : IDL.Func([IDL.Nat], [Dinosaur], ['query']),
  'getDinosaursByEra' : IDL.Func([IDL.Text], [IDL.Vec(Dinosaur)], ['query']),
  'getQuickFunFacts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DinosaurInput = IDL.Record({
    'era' : IDL.Text,
    'period' : IDL.Text,
    'diet' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'length' : IDL.Text,
    'interestingFact' : IDL.Text,
  });
  const Dinosaur = IDL.Record({
    'id' : IDL.Nat,
    'era' : IDL.Text,
    'period' : IDL.Text,
    'diet' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'length' : IDL.Text,
    'interestingFact' : IDL.Text,
  });
  
  return IDL.Service({
    'addDinosaur' : IDL.Func([DinosaurInput], [], []),
    'getAllDinosaurs' : IDL.Func([], [IDL.Vec(Dinosaur)], ['query']),
    'getDinosaurById' : IDL.Func([IDL.Nat], [Dinosaur], ['query']),
    'getDinosaursByEra' : IDL.Func([IDL.Text], [IDL.Vec(Dinosaur)], ['query']),
    'getQuickFunFacts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };